### ISSUE TITLE
Bug: main() references audio_program_generator.version, causing crash in virtual env w/o apg installed

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#24]
To make docopt print out the version, I referenced the current version as follows:
```
    this_version = pkg_resources.get_distribution("audio_program_generator").version

    args = docopt(__doc__, version=f"Audio Program Generator (apg) {this_version}")
```
However, if apg is not installed in the local virtual env, the reference fails:
```
Traceback (most recent call last):
  File "/Users/jeff/coding/audio_program_generator/audio_program_generator/apg.py", line 216, in <module>
    main()
  File "/Users/jeff/coding/audio_program_generator/audio_program_generator/apg.py", line 182, in main
    this_version = pkg_resources.get_distribution("audio_program_generator").version
  File "/Users/jeff/.pyenv/versions/apg-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "/Users/jeff/.pyenv/versions/apg-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/jeff/.pyenv/versions/apg-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/jeff/.pyenv/versions/apg-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'audio_program_generator' distribution was not found and is required by the application
```
Need to fix this.

**Comment by jeffwright13** [comment]
Fixed with branch issue24 (a8e1232)
