### ISSUE TITLE
Bug: code tries .close() method on None

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#26]
[Errno 2] No such file or directory: 'test2.txt'
Traceback (most recent call last):
  File "/Users/jeff/Library/Caches/pypoetry/virtualenvs/audio-program-generator-mt8qN5RX-py3.8/bin/apg", line 5, in <module>
    main()
  File "/Users/jeff/tmp/audio_program_generator/audio_program_generator/apg.py", line 207, in main
    pfile.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by bbelderbos** [comment]
Let's refactor this to use `with` statements only, I never liked this try/except/finally part I introduced here.

**Comment by jeffwright13** [comment]
Using the with statement on two files proved problematic, so I just coded around it by extending the "if pfile" logic used already on "if sfile."
