### ISSUE TITLE
Docker busted from 1.9.0 

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#54]
Also in 1.10.0.

```$ make apg
docker run --rm -it -v /Users/jwr003/coding/audio_program_generator/apgfiles:/audio_program_generator/apgfiles audio_program_generator:1.10.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'audio_program_generator.__main__'
make: *** [apg] Error 1
```

**Comment by jeffwright13** [comment]
Fresh repo pull of 1.10.0 and following instructions to the letter resulted in the docker build working just fine. Closing.
